version: "3.8"

services:
  nextcloud_db:
    image: postgres:12-alpine
    restart: always
    container_name: nextcloud_db
    logging:
      options:
        max-file: "4"
        max-size: "10m"
    ports:
      - 5432:5432
    networks:
      - nextcloud
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      LANG: de_DE.utf8
    volumes:
      - postgres:/var/lib/postgresql/data


  nextcloud:
    image: nextcloud:16-apache
    container_name: nextcloud
    restart: always
    depends_on:
      - nextcloud_db
    logging:
      options:
          max-file: "4"
          max-size: "10m"
    ports:
      - 80:80
    networks:
      - nextcloud
    volumes:
      - html:/var/www/html

networks:
  nextcloud:

volumes:
  postgres:
  html: